### ISSUE TITLE
Add Dataset with Time

### ISSUE THREAD

**Issue by forsman5** [speaq-ai/react-ui#49]
We need to add another dataset to our app that includes a time field, in order to test our time filtering new feature.

This means we also need to train Watson for this.

See #33

**Comment by forsman5** [comment]
https://www.kaggle.com/gustavomodelli/forest-fires-in-brazil

**Comment by jacobpa** [comment]
OSHP traffic dataset also has several time fields

**Comment by forsman5** [comment]
> OSHP traffic dataset also has several time fields

I can't find the dataset, only summaries online. Is this the dataset from mobikit that we tried to add earlier, but ran into some issues?
